openapi: 3.0.3
info:
  title: Todo Web Application API
  description: API for Todo Web Application with security features
  version: 1.0.0
  contact:
    name: API Support
    email: admin@example.com

servers:
  - url: https://api.todoapp.com/v1
    description: Production server
  - url: https://staging-api.todoapp.com/v1
    description: Staging server
  - url: http://localhost:8000/v1
    description: Development server

paths:
  /auth/login:
    post:
      summary: Authenticate user and return JWT token
      description: Validates user credentials and returns access token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: "johndoe"
                password:
                  type: string
                  format: password
                  example: "securePassword123"
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT access token
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  token_type:
                    type: string
                    example: "bearer"
        '401':
          description: Invalid credentials
        '422':
          description: Validation error

  /auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  example: "johndoe"
                email:
                  type: string
                  format: email
                  example: "john@example.com"
                password:
                  type: string
                  format: password
                  example: "securePassword123"
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: User already exists
        '422':
          description: Validation error

  /tasks:
    get:
      summary: Get all tasks for the authenticated user
      description: Returns a list of tasks owned by the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - insufficient permissions
    post:
      summary: Create a new task
      description: Creates a new task owned by the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - insufficient permissions
        '422':
          description: Validation error

  /tasks/{task_id}:
    get:
      summary: Get a specific task
      description: Returns details of a specific task if owned by the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - user does not own this task
        '404':
          description: Task not found
    put:
      summary: Update a specific task
      description: Updates a task if owned by the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - user does not own this task
        '404':
          description: Task not found
        '422':
          description: Validation error
    delete:
      summary: Delete a specific task
      description: Deletes a task if owned by the authenticated user
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - invalid or expired token
        '403':
          description: Forbidden - user does not own this task
        '404':
          description: Task not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        username:
          type: string
          example: "johndoe"
        email:
          type: string
          format: email
          example: "john@example.com"
        created_at:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"
    
    Task:
      type: object
      required:
        - id
        - title
        - owner_id
        - status
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174001"
        title:
          type: string
          example: "Complete project"
        description:
          type: string
          example: "Finish the important project by Friday"
        status:
          type: string
          enum: [pending, in-progress, completed]
          example: "pending"
        owner_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        created_at:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"
        due_date:
          type: string
          format: date-time
          example: "2023-01-05T00:00:00Z"
    
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: "New task"
        description:
          type: string
          example: "Description of the new task"
        status:
          type: string
          enum: [pending, in-progress, completed]
          default: "pending"
        due_date:
          type: string
          format: date-time
          example: "2023-01-05T00:00:00Z"
    
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          example: "Updated task title"
        description:
          type: string
          example: "Updated description"
        status:
          type: string
          enum: [pending, in-progress, completed]
          example: "in-progress"
        due_date:
          type: string
          format: date-time
          example: "2023-01-05T00:00:00Z"